### ISSUE TITLE
Zero normals for 3D cantilever example in stl export

### ISSUE THREAD

**Issue by jstults** [M2DOLab/OpenLSTO#1]
I've compiled the code and run the 2D examples successfully.  The 3D example project for the cantilever compliance minimization problem runs successfully, and exports an stl file to 'mystlfile.stl', but all of the normals in the file are "0 0 0."  This prevents it from being successfully opened with tools such as meshlab.  As a work-around, I was able to import the result stl file in to OpenSCAD and then export it to generate a file that has the appropriate normals in it.

**Comment by M2DOLab** [comment]
Hello. Thanks for the comment. The stl file can be visualized in Paraview as well, and Paraview can generate an stl file that has appropriate normals.

**Comment by jstults** [comment]
Thanks; I'll give Paraview a try too.

**Comment by CharlesFr** [comment]
Note that also `end loop` shouldn't have a space - this means it breaks on most imports.
