### ISSUE TITLE
How can OpenLSTO executes on windows?

### ISSUE THREAD

**Issue by mezzomax** [M2DOLab/OpenLSTO#11]
Hallo,

I want run this project on windows. But I don't know how to make it. Can you give me some help?

Best regards

**Comment by giacomo-b** [comment]
If you want to use the project `makefile` you'll need GNU Make, please see [this answer](https://stackoverflow.com/a/32127632/5617293). It looks like Makefile projects can also be [imported into Visual Studio](https://social.msdn.microsoft.com/Forums/en-US/0d553684-d589-4e5f-b04d-9b799f6d2e44/import-a-makefile-project?forum=Vsexpressvc), though I've never tried that.

As an alternative, you could create a Visual Studio project, import all files, and build the executable as if it were a native VS project.

**Comment by mezzomax** [comment]
Thanks for your answer. Now I use Ubuntu to run this code. But I meet a problem. 

I show it as follow

mezzomax@mezzomax-VirtualBox:~$ cd OpenLSTO/projects/compliance
mezzomax@mezzomax-VirtualBox:~/OpenLSTO/projects/compliance$ make main
g++ -std=c++14 -Wall -g -fopenmp -w -O3 -I./../../M2DO_FEA//include -I./../../M2DO_LSM//include -c -o ./../../M2DO_FEA/bin//solid_element.o ./../../M2DO_FEA//src/solid_element.cpp
./../../M2DO_FEA//src/solid_element.cpp: In member function ‘Eigen::MatrixXd M2DO_FEA::SolidElement::M()’:
./../../M2DO_FEA//src/solid_element.cpp:682:12: error: ‘h’ was not declared in this scope
   M_mat += h * rho * H_mat.transpose() * H_mat * w * J_mat.determinant() ;
                     ^
makefile:42: recipe for target '../../M2DO_FEA/bin//solid_element.o' failed
make: *** [../../M2DO_FEA/bin//solid_element.o] Error 1
mezzomax@mezzomax-VirtualBox:~/OpenLSTO/projects/compliance$

**Comment by giacomo-b** [comment]
`h` is not being initialized. Go to _M2DO_FEA/include/solid_element.h_ and add the declaration `double h = 1.0;` among the public member variables. Sorry about that. See pull request https://github.com/M2DOLab/OpenLSTO/pull/10.

**Comment by mezzomax** [comment]
Thanks !
A problem is occurred when I try the benchmark for stress minimization.
I follow the step in the guide
1. cd projects/stress_min
2. make lbeam
Then  a fatal error: M2DO_FEA.h: No such file or directory
- #include "M2DO_FEA.h"
                 ^
compilation terminated.
<build-in>: recipe for target 'lbeam' failed
make: *** [lbeam] Error 1

This is very strange. Other examples (compliance and hole_creation) have no such problem.

**Comment by mezzomax** [comment]
May be it caused by the Eigen3 files. Is this open source code need to install the eigen3 ?

**Comment by giacomo-b** [comment]
The problem is that there's no target named _lbeam_, you want to call [_main_](https://github.com/M2DOLab/OpenLSTO/blob/f799924afda60bc3ea352d2ad4af163f600c9df9/projects/stress_min/makefile#L58):
1. `cd projects/stress_min`
2. `make main`

Eigen should work fine, it's library of just headers and there is no need to install it. And yes, [it's open source](https://gitlab.com/libeigen/eigen).

**Comment by mezzomax** [comment]
Thanks, it works well now!
