### ISSUE TITLE
Other geometry than cuboid for 3D optimization

### ISSUE THREAD

**Issue by GuilleNM** [M2DOLab/OpenLSTO#14]
Hi,

I was trying to work out how to generate initial geometries for the optimizations in 3d with for example a hollow square beam. I saw that there were some functions like LevelSet3D::MakeLBeam() and LevelSet3D::Advect_LBeam(). I tried to use them but it keeps given the "Segmentation fault (code dumped)" error.

Is there a way to make different shapes, like in the stress minimization example, doing the L shape by using the kill_region function?

Thanks!

**Comment by carolinaj** [comment]
Hi, 

So unfortunately, the 3D version is very simple and doesn't have the functionality to create the type of initial geometry you're looking for. We will be releasing a 3D version of our code that has more functionality within the next few weeks, but that will be its own separate repository.

**Comment by skbizport** [comment]
Can you pls share location of this separate repository?

Thx
