### ISSUE TITLE
Uninitialized variable in lsm_hole_insertion.hpp

### ISSUE THREAD

**Issue by elidim** [M2DOLab/OpenLSTO#3]
When compiling the hole_creation example, my compiler (Visual C++) produces an error due to the uninitialized variable `h` occurring here: https://github.com/M2DOLab/OpenLSTO/blob/master/projects/hole_creation/lsm_hole_insertion.hpp#L324
`h` is not set to any value, it is only declared on line 245:
https://github.com/M2DOLab/OpenLSTO/blob/master/projects/hole_creation/lsm_hole_insertion.hpp#L245
Since `h` is  described as "unit length of element in level set mesh", it seems logical that it should have some non-zero value. Thanks in advance!

**Comment by carolinaj** [comment]
Hi @elidim, please set `double h = 1.0;`. The function that uses the `h` variable, `initialise_hole_lsf`, isn't actually used in the main.cpp, so this shouldn't affect the execution fo the program. Please let me know if you encounter any more problems or if this doesn't fix your issue.
