### ISSUE TITLE
Mass matrix does not scale with thickness

### ISSUE THREAD

**Issue by giacomo-b** [M2DOLab/OpenLSTO#7]
While extending the code for supporting an eigenfrequencies problem (for which I need the mass matrix), I noticed that `SolidElement::M()` returns a matrix `M_mat` which does not depend on the thickness of the element (specified as `h` in `SolidMaterial :: SolidMaterial (int spacedim, double E, double nu, double rho, double alphaT, double h)`).
No matter the imposed thickness, the mass matrix always assumes it to be unitary, I believe there is a missing `h` in the `SolidElement::M()` method, correct me if I'm wrong.

**Comment by carolinaj** [comment]
Yes, there does need to be a multiplication by the thickness `h` in `SolidElement::M()`. Thanks for pointing this out.
